services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: squadron_frontend
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      NODE_ENV: production
      PORT: 3000
      NEXT_PUBLIC_API_URL: http://localhost:1337
      INTERNAL_API_URL: http://cms:1337
    depends_on:
      - cms
    ports:
      - "3000:3000"
    networks:
      - app_network

  cms:
    build:
      context: ./cms
      dockerfile: Dockerfile
    container_name: squadron_cms
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      NODE_ENV: production
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
#    command: npm run develop
    depends_on:
      - db
    ports:
      - "1337:1337"
    volumes:
      - ./cms/public/uploads:/opt/app/public/uploads
    networks:
      - app_network

  db:
    image: postgres:16-alpine
    container_name: squadron_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge